# ----------------------------------------------------
# This file is generated by the Qt Visual Studio Add-in.
# ------------------------------------------------------


HEADERS += ./ProcessHandler.h
SOURCES += ./main.cpp \
    ./ProcessHandler.cpp
